# file: ansible-role-llvm/tasks/source.yml

- name: LLVM | clean tmp dir
  file:
    state: absent
    path: "{{ llvm_tmp }}"

- name: LLVM | clean build dir
  file:
    state: absent
    path: "{{ llvm_build_dir }}"

- name: LLVM | get from git repository
  git: repo="{{ llvm_repo_url }}"
       dest="{{ llvm_tmp }}"
       version="{{ version }}"
  register: llvm_downloaded

- name: CLANG | get from git repository
  become: true
  git: repo="{{ clang_repo_url }}"
       dest="{{ clang_tmp }}"
       version="{{ version }}"
  when: llvm_downloaded.changed

- name: CLANG_EXTRA_TOOLS | get from git repository
  become: true
  git: repo="{{ clang_extra_tools_repo_url }}"
       dest="{{ clang_extra_tools_tmp }}"
       version="{{ version }}"
  when: llvm_downloaded.changed

- name: LLVM | Make LLVM build folder
  become: true
  file: path="{{ llvm_build_dir }}" state=directory
  when: llvm_downloaded.changed

- name: LLVM | run cmake
  command:  chdir="{{ llvm_build_dir }}" \
            cmake -G "Unix Makefiles" {{ llvm_tmp }} \
            -DCMAKE_C_COMPILER={{gcc_install_dir}}/bin/gcc \
            -DCMAKE_CXX_COMPILER={{gcc_install_dir}}/bin/g++ \
            -DGCC_INSTALL_PREFIX={{gcc_install_dir}} \
            -DCMAKE_CXX_LINK_FLAGS="-L{{gcc_install_dir}}/lib64 -Wl,-rpath,{{gcc_install_dir}}/lib64" \
            -DCMAKE_INSTALL_RPATH="{{gcc_install_dir}}/lib64" \
            -DCMAKE_INSTALL_PREFIX={{llvm_install_dir}} \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DCMAKE_BUILD_TYPE="Release" \
            -DLLVM_TARGETS_TO_BUILD="X86" {{ llvm_tmp }}
  when: llvm_downloaded.changed

- name: LLVM | make
  become: true
  command: chdir="{{ llvm_build_dir }}" make
  when: llvm_downloaded.changed

- name: LLVM | install
  become: true
  command: chdir="{{ llvm_build_dir }}" make install
  when: llvm_downloaded.changed

- name: LLVM | add path to /etc/ld.so.conf.d/
  become: true
  action: template src=llvm.conf-template.j2
          dest="/etc/ld.so.conf.d/llvm-{{llvm_version}}.conf"
          mode=0644
  when: llvm_downloaded.changed

- name: LLVM | run ldconfig
  become: true
  shell: ldconfig
  when: llvm_downloaded.changed

- name: LLVM | add path to /etc/profile.d
  become: true
  action: template src=llvm.sh-template.j2
          dest="/etc/profile.d/llvm.sh"
          mode=0644
  when: llvm_downloaded.changed
