---
# file: ansible-role-llvm/tasks/source.yml

# - name: LLVM | clean tmp dir
#   file:
#     state: absent
#     path: "{{ llvm_tmp }}"

# - name: LLVM | clean build dir
#   file:
#     state: absent
#     path: "{{ llvm_build_dir }}"


# - name: LLVM | check if LLVM is already installed
#   ansible.builtin.command: llvm-config --version
#   register: llvm_exists

- name: LLVM | check if LLVM is already installed
  shell: command -v llvm-config >/dev/null 2>&1
  register: llvm_exists
  ignore_errors: yes

- debug: msg="{{ llvm_exists.rc }}" # it returns rc 1
- debug: var=llvm_exists

- name: LLVM | get from git repository
  git: repo="{{ llvm_repo_url }}"
       dest="{{ llvm_tmp }}"
       version="{{ version }}"
  when: not llvm_exists.rc == 0
  register: llvm_downloaded

- name: LLVM | Make LLVM build folder
  become: true
  file: path="{{ llvm_build_dir }}" state=directory
  when: llvm_downloaded.changed

- name: LLVM | wat
  debug:
    msg: "ansible_architecture.stdout: {{ ansible_architecture }}"

- name: LLVM | run cmake x86
  command:  chdir="{{ llvm_build_dir }}" \
            cmake -G "Unix Makefiles" {{ llvm_tmp }} \
            -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt" \
            -DCMAKE_INSTALL_PREFIX={{llvm_install_dir}} \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DCMAKE_BUILD_TYPE="Release" \
            -DLLVM_TARGETS_TO_BUILD="X86" \
            {{ llvm_tmp }}/llvm
  when:
    - llvm_downloaded.changed
    - ansible_architecture == "x86_64"
  register: llvm_cmake

- name: LLVM | run cmake aarch64
  command:  chdir="{{ llvm_build_dir }}" \
            cmake -G "Unix Makefiles" {{ llvm_tmp }} \
            -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt" \
            -DCMAKE_INSTALL_PREFIX={{llvm_install_dir}} \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DCMAKE_BUILD_TYPE="Release" \
            -DLLVM_TARGETS_TO_BUILD="AArch64" \
            {{ llvm_tmp }}/llvm
  when:
    - llvm_downloaded.changed
    - ansible_architecture == "aarch64"
  register: llvm_cmake

- name: LLVM | wat llvm_cmake
  debug:
    msg: "llvm_cmake: {{ llvm_cmake }}"

- name: LLVM | make
  become: true
  command: chdir="{{ llvm_build_dir }}" make -j{{llvm_number_build_jobs}}
  when: llvm_cmake.changed
  register: llvm_make

- name: LLVM | install
  become: true
  command: chdir="{{ llvm_build_dir }}" make install
  when: llvm_make.changed
  register: llvm_install

# - name: LLVM | add path to /etc/ld.so.conf.d/
#   become: true
#   action: template src=llvm.conf-template.j2
#           dest="/etc/ld.so.conf.d/llvm-{{version}}.conf"
#           mode=0644
#   when: llvm_install.changed

# - name: LLVM | run ldconfig
#   become: true
#   shell: ldconfig
#   when: llvm_install.changed

# - name: LLVM | add path to /etc/profile.d
#   become: true
#   action: template src=llvm.sh-template.j2
#           dest="/etc/profile.d/llvm.sh"
#           mode=0644
#   when: llvm_install.changed

- name: LLVM | cleanup build
  become: true
  file:
    path: "{{ llvm_build_dir }}"
    state: absent
  when: llvm_install.changed

- name: LLVM | cleanup tmp
  become: true
  file:
    path: "{{ llvm_tmp }}"
    state: absent
  when: llvm_install.changed

...
