---
# file: ansible-role-llvm/tasks/source.yml

# - name: LLVM | clean tmp dir
#   file:
#     state: absent
#     path: "{{ llvm_tmp }}"

# - name: LLVM | clean build dir
#   file:
#     state: absent
#     path: "{{ llvm_build_dir }}"


# - name: LLVM | check if LLVM is already installed
#   ansible.builtin.command: llvm-config --version
#   register: llvm_exists

- name: LLVM | check if LLVM is already installed
  shell: command -v llvm-config >/dev/null 2>&1
  register: llvm_exists
  ignore_errors: yes

- debug: msg="{{ llvm_exists.rc }}" # it returns rc 1
- debug: var=llvm_exists

- name: LLVM | get from ftp
  ansible.builtin.unarchive:
    src: "{{ llvm_repo_url }}/{{ version }}.zip"
    dest: "{{ llvm_tmp }}"
    remote_src: yes
  when: not llvm_exists.rc == 0
  register: llvm_downloaded


# https://reviews.llvm.org/D89450
- name: LLVM | apply patch
  ansible.posix.patch:
    remote_src=no
    src=limits.patch
  when: llvm_downloaded.changed and version == "llvmorg-12.0.1"

- name: LLVM | Make LLVM build folder
  become: true
  file: path="{{ llvm_build_dir }}" state=directory
  when: llvm_downloaded.changed

- name: LLVM | wat
  debug:
    msg: "ansible_architecture.stdout: {{ ansible_architecture }}"

- name: LLVM | run cmake x86
  command:  chdir="{{ llvm_build_dir }}" \
            cmake -G "Unix Makefiles" {{ llvm_tmp }} \
            -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt" \
            -DCMAKE_INSTALL_PREFIX={{llvm_install_dir}} \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ENABLE_RTTI=ON \
            -DCMAKE_BUILD_TYPE="Release" \
            -DLLVM_TARGETS_TO_BUILD="X86" \
            "{{ llvm_tmp }}/llvm-project-{{version}}"
  when:
    - llvm_downloaded.changed
    - ansible_architecture == "x86_64"
  #register: llvm_cmake

- name: LLVM | run cmake aarch64
  command:  chdir="{{ llvm_build_dir }}" \
            cmake -G "Unix Makefiles" {{ llvm_tmp }} \
            -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt" \
            -DCMAKE_INSTALL_PREFIX={{llvm_install_dir}} \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ENABLE_RTTI=ON \
            -DCMAKE_BUILD_TYPE="Release" \
            -DLLVM_TARGETS_TO_BUILD="AArch64" \
            "{{ llvm_tmp }}/llvm-project-{{version}}"
  when:
    - llvm_downloaded.changed
    - ansible_architecture == "aarch64"
  #register: llvm_cmake

# - name: LLVM | wat llvm_cmake
#   debug:
#     msg: "llvm_cmake: {{ llvm_cmake }}"

- name: LLVM | make
  become: true
  command: chdir="{{ llvm_build_dir }}" make -j{{llvm_number_build_jobs}}
  when: llvm_downloaded.changed
  register: llvm_make

- name: LLVM | install
  become: true
  command: chdir="{{ llvm_build_dir }}" make install
  when: llvm_make.changed
  register: llvm_install

# - name: LLVM | add path to /etc/ld.so.conf.d/
#   become: true
#   action: template src=llvm.conf-template.j2
#           dest="/etc/ld.so.conf.d/llvm-{{version}}.conf"
#           mode=0644
#   when: llvm_install.changed

# - name: LLVM | run ldconfig
#   become: true
#   shell: ldconfig
#   when: llvm_install.changed

# - name: LLVM | add path to /etc/profile.d
#   become: true
#   action: template src=llvm.sh-template.j2
#           dest="/etc/profile.d/llvm.sh"
#           mode=0644
#   when: llvm_install.changed

- name: LLVM | cleanup build
  become: true
  file:
    path: "{{ llvm_build_dir }}"
    state: absent
  when: llvm_install.changed

- name: LLVM | cleanup tmp
  become: true
  file:
    path: "{{ llvm_tmp }}/llvm-project-{{version}}"
    state: absent
  when: llvm_install.changed

...
