# file: ansible-role-llvm/tasks/source.yml

- name: LLVM | get from git repository
  git: repo="{{ llvm_repo_url }}"
       dest="{{ llvm_tmp }}"
       version="{{ llvm_version }}"
  register: llvm_downloaded

- name: CLANG | get from git repository
  git: repo="{{ clang_repo_url }}"
       dest="{{ clang_tmp }}"
       version="{{ clang_version }}"
  register: clang_downloaded

- name: LLVM | Creates build directory
  file:
    path: "{{ llvm_build_dir }}"
    state: directory
